import type { Metadata } from "next";
import { Epilogue, Sofia } from "next/font/google";
import "./globals.css";
import "./head.css";

// Configuración de Epilogue (Fuente de cuerpo y títulos)
const epilogue = Epilogue({
  subsets: ["latin"],
  variable: "--font-epilogue", // Variable que usará Tailwind
  weight: ["300", "400", "500", "600", "700"],
});

// Configuración de Sofia (Fuente tipo firma/cursiva)
const sofia = Sofia({
  subsets: ["latin"],
  variable: "--font-sofia", // Variable que usará Tailwind
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <head>
        {/* Importamos los iconos que no vienen en next/font */}
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap" rel="stylesheet" />
      </head>
      <body
        className={`${epilogue.variable} ${sofia.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
