import type { Metadata } from "next";
import { Epilogue, Sofia } from "next/font/google";
import "./globals.css";
import "./style.css";
import Footer from "@/components/layout/Footer";

// Configuración de Epilogue (Fuente de cuerpo y títulos)
const epilogue = Epilogue({
  subsets: ["latin"],
  variable: "--font-epilogue", // Variable que usará Tailwind
  weight: ["300", "400", "500", "600", "700"],
});

// Configuración de Sofia (Fuente tipo firma/cursiva)
const sofia = Sofia({
  subsets: ["latin"],
  variable: "--font-sofia", // Variable que usará Tailwind
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="bg-luxury-black min-h-screen flex flex-col">
      <main className="flex-1">{children}</main>
   
    </div>
  );
}
